name: UnitTest

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
    - name: Install dependencies
      run: pipenv install
    - name: Test
      run: pipenv run pytest -s